### ISSUE TITLE
Broken - blank display

### ISSUE THREAD

**Issue by a4v2d4** [dos-2/oddshub#5]
### Background
Running on 9/15/2024 at 1:30 pm PST, and there are many MLB and NFL games today.
- **OS:** macOS Sonoma 14.6.1
- **go version**: 1.22.5

### Issue
UI displays nothing for NFL nor MLB:
![Screenshot 2024-09-15 at 1 24 55 PM](https://github.com/user-attachments/assets/6691d33b-2d59-4c98-b4a8-f3dcff2e620c)

**Comment by dos-2** [comment]
Thank you so much for using oddshub! There was an issue with the api key. It should be working now, please give an update here that it works on your end, thanks again!

**Comment by dos-2** [comment]
@a4v2d4 No option for that yet, but I can definitely get on adding that. Thanks so much!!
